# Install packages
apm install atom-clock
apm install atom-ide-ui
apm install atom-keyboard-macros-vim
apm install atom-keyboard-macros-vim
apm install atom-latex
apm install atom-python-run
apm install audio
apm install autoclose-html
apm install autocomplete-haskell
apm install autocomplete-java
apm install busy-signal
apm install color-picker
apm install docblockr
apm install ex-mode
apm install file-icons
apm install git-log
apm install glsl-preview
apm install hard-wrap
apm install hey-pane
apm install highlight-selected
apm install hydrogen
apm install ide-c
apm install ide-cpp
apm install ide-html
apm install ide-java
apm install ide-php
apm install ide-python
apm install intentions
apm install java-generator
apm install language-arm
apm install language-glsl
apm install language-haskell
apm install language-latex
apm install language-matlab
apm install language-prolog
apm install language-viml
apm install latex-completions
apm install linter-gcc
apm install linter-matlab
apm install linter-spell-latexsimple
apm install linter-ui-default
apm install linter-write-good
apm install markdown-preview-plus
apm install minimap
apm install minimap-codeglance
apm install minimap-cursorline
apm install minimap-find-and-replace
apm install minimap-git-diff
apm install minimap-highlight-selected
apm install minimap-linter
apm install minimap-pigments
apm install minimap-selection
apm install pdf-view
apm install pigments
apm install platformio-ide-terminal
apm install python-indent
apm install python-tools
apm install relative-numbers
apm install teletype
apm install tool-bar
apm install tool-bar-atom
apm install tree-view-git-status
apm install vim-mode-plus
apm install vim-mode-plus-keymaps-for-surround
apm install vim-mode-plus-move-selected-text
apm install zentabs
